### PR TITLE
Basic http/https scheme

### PR DESCRIPTION
**Pull request by ids1024**
Run `hyperd http` and `hyperd https` to start it.

### CODE REVIEW

**Comment by dawid2193487** [comment]
This allows http connections to be handled like files, making something like  `editor https://example.foo/bar.md` or `viewer http://foo.bar/image.png` possible?

Maybe writing to the file could somehow be used to make POST requests?

**Comment by ids1024** [comment]
hyperdtest

(I was going to use the Redox logo, but it didn't show up because it's black on alpha.)

> Maybe writing to the file could somehow be used to make POST requests?

That should be doable. I guess a process would have to open the url read/write, (or just read, if no response is need), write the post data, then read the response. I guess it would have to send the request at the first read? And make it a POST request if data is written to it, GET otherwise.

**Comment by ids1024** [comment]
`cat http(s)://...` using this is noticeably slower than `wget`; I'm not entirely sure why, or how that can be improved.

**Comment by ids1024** [comment]
@jackpot51 What do you think of this?

**Comment by xTibor** [comment]
I tried this with the new smol network stack and I don't feel any noticeable difference between the scheme and `wget` now. Couldn't measure them accurately but the performance was always in the same ballpark.

**Pull request closed without merging**
