### PR TITLE
whois: Use existing redox-os libraries

### PR DESCRIPTION
**Pull request by Abogical**
This makes the utlilty parse arguments via ArgParser and use extra::io::fail when failing. Also fixes a small spelling mistake.

### CODE REVIEW

**Comment by jackpot51** [comment]
Can you rebase it on the latest master?

**Comment by Abogical** [comment]
Hold on, I'm doing that.

**Comment by Abogical** [comment]
Done. cherrypicking was alot easier.

**Comment by jackpot51** [comment]
Sweet!

**Pull request merged**
